# Generated by Django 6.0.2 on 2026-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('topic_type', models.CharField(choices=[('PLANET', 'Planet'), ('STAR', 'Star'), ('COSMOLOGY', 'Cosmology'), ('GALAXY', 'Galaxy'), ('MISSION', 'Mission')], max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['topic_type', 'title'],
            },
        ),
    ]
